config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :fedex_labels, only: [:index, :show, :create, :new, :new_label_us_shipper]
  resources :fedex_labels do
    get 'download', on: :member
  end
  root "fedex_labels#index"
  get '/new_fedex_label_with_us_recipient',        :to => 'fedex_labels#new_fedex_label_with_us_recipient',  as: :new_fedex_label_with_us_recipient
  get '/new_fedex_label_with_ca_recipient',        :to => 'fedex_labels#new_fedex_label_with_ca_recipient',  as: :new_fedex_label_with_ca_recipient
  get '/new_fedex_label_with_jp_recipient',        :to => 'fedex_labels#new_fedex_label_with_jp_recipient',  as: :new_fedex_label_with_jp_recipient

  post '/create_international',        :to => 'fedex_labels#create_international',  as: :create_international



end

app/models/fedex_label.rb
class FedexLabel < ApplicationRecord
    
end

app/controllers/fedex_labels_controller.rb
class FedexLabelsController < ApplicationController
  def index
    @labels = FedexLabel.all
    @version_info = FedexLabelService.new.version_info
  end

  def show
    @label = FedexLabel.find(params[:id])
  end

  def new
    @shipper = {}

    @recipient = {}

    @packages = []
    @packages << {
      weight: { units: 'LB', value: 2 },
      dimensions: { length: 10, width: 5, height: 4, units: 'IN' }
    }
    # packages << {
    #   :weight => {:units => "LB", :value => 6},
    #   :dimensions => {:length => 5, :width => 5, :height => 4, :units => "IN" }
    # }

    @shipping_options = {
      packaging_type: 'YOUR_PACKAGING',
      drop_off_type: 'REGULAR_PICKUP'
    }

    @payment_options = {
      type: 'THIRD_PARTY',
      account_number: '123456789',
      name: 'Third Party Payor',
      company: 'Company',
      phone_number: '555-555-5555',
      country_code: 'US'
    }

    @example_spec = {
      image_type: 'EPL2', #PDF
      label_stock_type: 'STOCK_4X6'
    }
  end

  def new_fedex_label_with_us_recipient
    @shipper = { name: 'Sender',
                 company: 'Company',
                 phone_number: '555-555-5555',
                 address: '1202 Chalet Ln',
                 city: 'Harrison',
                 state: 'AR',
                 postal_code: '72601',
                 country_code: 'US' }

    @recipient = { name: 'Recipient',
                   company: 'Company',
                   phone_number: '555-555-5555',
                   address: 'Main Street',
                   city: 'Franklin Park',
                   state: 'IL',
                   postal_code: '60131',
                   country_code: 'US',
                   residential: 'false' }

    @packages = []
    @packages << {
      weight: { units: 'LB', value: 2 },
      dimensions: { length: 10, width: 5, height: 4, units: 'IN' }
    }
    # packages << {
    #   :weight => {:units => "LB", :value => 6},
    #   :dimensions => {:length => 5, :width => 5, :height => 4, :units => "IN" }
    # }

    @shipping_options = {
      packaging_type: 'YOUR_PACKAGING',
      drop_off_type: 'REGULAR_PICKUP'
    }

    @payment_options = {
      type: 'THIRD_PARTY',
      account_number: '123456789',
      name: 'Third Party Payor',
      company: 'Company',
      phone_number: '555-555-5555',
      country_code: 'US'
    }

    @example_spec = {
      image_type: 'EPL2',
      label_stock_type: 'STOCK_4X6'
    }
    render 'new'
  end

  def new_fedex_label_with_ca_recipient
    @recipient = { name: 'Recipient', company: 'Company', phone_number: '555-555-5555',
                   address: 'Address Line 1', city: 'Richmond', state: 'BC', postal_code: 'V7C4V4', country_code: 'CA', residential: 'true' }
    @shipper = { name: 'Sender',
                 company: 'Company',
                 phone_number: '555-555-5555',
                 address: '1202 Chalet Ln',
                 city: 'Harrison',
                 state: 'AR',
                 postal_code: '72601',
                 country_code: 'US' }

    @packages = [
      {
        weight: { units: 'LB', value: 6 },
        dimensions: { length: 5, width: 5, height: 4, units: 'IN' }
      }
    ]
    @example_spec = {
      image_type: 'EPL2',
      label_stock_type: 'STOCK_4X6'
    }
    @shipping_options = {
      packaging_type: 'YOUR_PACKAGING',
      drop_off_type: 'REGULAR_PICKUP'
    }
    @customs = {
      duties_payment: {
        payment_type: 'SENDER',
        payor: {
          responsible_party: {
            account_number: ENV['FEDEX_ACCOUNT_NUMBER'],
            contact: {
              person_name: 'Mr. Test',
              phone_number: '12345678'
            }
          }
        }
      },
      document_content: 'NON_DOCUMENTS',
      customs_value: {
        currency: 'USD', # UK Pounds Sterling
        amount: 155.79
      },
      commercial_invoice: {
        terms_of_sale: 'DDU'
      },
      commodities: [
        {
          number_of_pieces: 1,
          description: 'Pink Toy',
          country_of_manufacture: 'GB',
          weight: {
            units: 'LB',
            value: 2
          },
          quantity: 1,
          quantity_units: 'EA',
          unit_price: {
            currency: 'USD',
            amount: 155.79
          },
          customs_value: {
            currency: 'USD',
            amount: 155.79
          }
        }
      ]
    }
    render 'new_ca'
  end

  def new_fedex_label_with_jp_recipient
    @shipper = { name: 'Sender',
                 company: 'Company',
                 phone_number: '555-555-5555',
                 address: '1202 Chalet Ln',
                 city: 'Harrison',
                 state: 'AR',
                 postal_code: '72601',
                 country_code: 'US' }

    @recipient = { name: 'Yasuda Saki',
                   company: 'Japan Grocery Inc.',
                   phone_number: '555-555-5555',
                   address: 'Times, South Tanaka Nakacho Asahicho Line',
                   city: 'Tokyo',
                   postal_code: '179-0074',
                   country_code: 'JP',
                   residential: 'false' }

    @packages = [
      {
        weight: { units: 'LB', value: 6 },
        dimensions: { length: 5, width: 5, height: 4, units: 'IN' }
      }
    ]
    
    render 'new_jp'
  end

  def create
    fedex = Fedex::Shipment.new(key: ENV['FEDEX_KEY'],
                                password: ENV['FEDEX_PASSWORD'],
                                account_number: ENV['FEDEX_ACCOUNT_NUMBER'],
                                meter: ENV['FEDEX_METER'],
                                mode: ENV['FEDEX_MODE'])

    shipper = params[:shipper]
    recipient = params[:recipient]

    packages = []
    packages << {
      weight: { units: 'LB', value: 2 },
      dimensions: { length: 10, width: 5, height: 4, units: 'IN' }
    }

    # packages << {
    #   :weight => {:units => "LB", :value => 6},
    #   :dimensions => {:length => 5, :width => 5, :height => 4, :units => "IN" }
    # }
    shipping_options = {
      packaging_type: 'YOUR_PACKAGING',
      drop_off_type: 'REGULAR_PICKUP'
    }

    payment_options = {
      type: 'THIRD_PARTY',
      account_number: '123456789',
      name: 'Third Party Payor',
      company: 'Company',
      phone_number: '555-555-5555',
      country_code: 'US'
    }

    example_spec = {
      image_type: 'EPL2',
      label_stock_type: 'STOCK_4X6'
    }

    label = fedex.label(filename: '/home/dev/fedex_solution/bunny.pcx',
                        shipper:,
                        recipient:,
                        packages:,
                        service_type: 'FEDEX_GROUND',
                        shipping_options:,
                        label_specification: example_spec)

    FedexLabel.create(image: label.image, options: label.options, response_details: label.response_details)
    redirect_to fedex_labels_path
  end

  def create_international
    service = FedexLabelService.new
    service.set_shipper(params[:shipper].to_unsafe_h)
    service.set_recipient(params[:recipient].to_unsafe_h)
    
    service.set_service_type("FEDEX_GROUND") # works fine in Canada
    
    # service.set_service_type("SMART_POST") 
    
    # service.service_type = "INTERNATIONAL_PRIORITY" # work in Japan
    # service.set_service_type("INTERNATIONAL_ECONOMY") # work in Japan
    # service.service_type = "INTERNATIONAL_PRIORITY"  # INTERNATIONAL_FIRST, INTERNATIONAL_PRIORITY, INTERNATIONAL_ECONOMY, INTERNATIONAL_PRIORITY_FREIGHT, INTERNATIONAL_ECONOMY_FREIGHT

    packages = [
      {
        weight: { units: 'LB', value: 6 },
        dimensions: { length: 5, width: 5, height: 4, units: 'IN' }
      }
    ]
    service.set_packages(packages)
    
    ca_customs_details = service.send(:ca_customs_details)
    ex_document =  service.send(:ex_document)
    ex_filenames =  service.send(:ex_filenames)

    service.set_shipping_document(ex_document)
    service.set_filenames(ex_filenames)

    label = service.generate_label(ca_customs_details)
    
    FedexLabel.create(image: label.image, options: label.options, response_details: label.response_details)
    redirect_to fedex_labels_path
  end

  def download
    @label = FedexLabel.find(params[:id])
    send_data @label.image, filename: 'label.pdf', type: 'application/pdf', disposition: 'inline'
  end


  def generate_labels(service_type, label_stock_type)
    service = FedexLabelService.new

    recipient = { name: 'Recipient', company: 'Company', phone_number: '555-555-5555',
                   address: 'Address Line 1', city: 'Richmond', state: 'BC', postal_code: 'V7C4V4', country_code: 'CA', residential: 'true' }
    shipper = { name: 'Sender',
                 company: 'Company',
                 phone_number: '555-555-5555',
                 address: '1202 Chalet Ln',
                 city: 'Harrison',
                 state: 'AR',
                 postal_code: '72601',
                 country_code: 'US' }


    service.set_shipper(shipper)
    service.set_recipient(recipient)
    
    service.set_service_type("FEDEX_GROUND") # works fine in Canada
    
    # service.set_service_type("SMART_POST") 
    
    # service.service_type = "INTERNATIONAL_PRIORITY" # work in Japan
    # service.set_service_type("INTERNATIONAL_ECONOMY") # work in Japan
    # service.service_type = "INTERNATIONAL_PRIORITY"  # INTERNATIONAL_FIRST, INTERNATIONAL_PRIORITY, INTERNATIONAL_ECONOMY, INTERNATIONAL_PRIORITY_FREIGHT, INTERNATIONAL_ECONOMY_FREIGHT

    packages = [
      {
        weight: { units: 'LB', value: 6 },
        dimensions: { length: 5, width: 5, height: 4, units: 'IN' }
      }
    ]
    service.set_packages(packages)
    
    ca_customs_details = service.send(:ca_customs_details)
    ex_document =  service.send(:ex_document)
    ex_filenames =  service.send(:ex_filenames)

    service.set_shipping_document(ex_document)
    service.set_filenames(ex_filenames)

    service.set_label_specification({

app/helpers/fedex_labels_helper.rb
module FedexLabelsHelper
end

app/views/fedex_labels/index.html.erb
<div class="pt-5 container">

  <h1>FedEx Labels</h1>
  <code>
    <%= @version_info %>
  </code>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Service Type</th>
      <th>Label Stock Type</th>
      <th>Options Type</th>
      <th>Job ID(Response Details)</th>
      <th>Download</th>
    </tr>

    <% @labels.each do |label| %>
      <tr>
          <td><a href="/fedex_labels/<%= label.id %>"><%= label.id %></a></td>
          <td><a href="/fedex_labels/<%= label.service_type %>"><%= label.service_type %></a></td>
          <td><a href="/fedex_labels/<%= label.label_stock_type %>"><%= label.label_stock_type %></a></td>
          <td><a href="/fedex_labels/<%= label.id %>"><%= label.options['type'] %></a></td>
          <td><a href="/fedex_labels/<%= label.id %>"><%= label.response_details['job_id'] %></a></td>
          <td><%= link_to 'Download', download_fedex_label_path(label) %></td>
      </tr>
    <% end %>
  </table>

  <ul class="pt-4">
    <li>
        <%= link_to "Test - New a FedEx Label", new_fedex_label_path %>
    </li>
    <li>
        <%= link_to "Test - New a FedEx Label with US Shipper", new_fedex_label_with_us_recipient_path %>
    </li>
    <li>
        <%= link_to "Test - New a FedEx Label with CA recipient", new_fedex_label_with_ca_recipient_path %>
    </li>
    <li>
        <%= link_to "Test - New a FedEx Label with JP recipient", new_fedex_label_with_jp_recipient_path %>
    </li>
  </ul>

</div>

app/views/fedex_labels/new.html.erb
<div class="container">
    <%= form_with url: "/fedex_labels", method: :post do |form| %>
    <div class="row">
        <ul class="pt-5">
            <li>
                <%= link_to "Go Home - FedEx Labels", fedex_labels_path %>
            </li>
        </ul>
        <h1>New FedEx Label</h1>
        
        <div class="col-6">
            <h3>Shipper Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="shipper[name]" value="<%=@shipper[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="shipper[company]" value="<%=@shipper[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="shipper[phone_number]" value="<%=@shipper[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="shipper[address]" value="<%=@shipper[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="shipper[city]" value="<%=@shipper[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="shipper[state]" value="<%=@shipper[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="shipper[postal_code]" value="<%=@shipper[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text"  name="shipper[country_code]" value="<%=@shipper[:country_code] %>">
            </div>
        </div>
        <div class="col-6">
            <h3>Recipient Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="recipient[name]" value="<%=@recipient[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="recipient[company]" value="<%=@recipient[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="recipient[phone_number]" value="<%=@recipient[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="recipient[address]" value="<%=@recipient[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="recipient[city]" value="<%=@recipient[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="recipient[state]" value="<%=@recipient[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="recipient[postal_code]" value="<%=@recipient[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text" name="recipient[country_code]" value="<%=@recipient[:country_code] %>">
            </div>
            <div class="form-fild">
                <label>Residential :</label>
                <input type="text" name="recipient[residential]" value="<%=@recipient[:residential] %>">
            </div>
        </div>
        
    </div>
    <div class="row">
        <h3>Package Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @packages.inspect %>
        </code>
        
        <h3>Example Spec Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @example_spec.inspect %>
        </code>

        <h3>Shipping Options</h3>
        <hr/>
        <code class="pb-3">
            <%= @shipping_options.inspect %>
        </code>
        
        <h3>Customs Clearance Detail</h3>
        <hr/>
        <code class="pb-3">
            <%= @customs.inspect %>
        </code>
    </div>
    <div class="form-fild">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
    <% end %>

</div>



<script>
$('.form-fild input,.form-fild textarea').focus(function() {
    $(this).parent().addClass('open');
});

$('.form-fild input,.form-fild textarea').blur(function() {
    $(this).parent().removeClass('open');
});
</script>

app/views/fedex_labels/new_ca.html.erb
<div class="container">
    <%= form_with url: "/create_international", method: :post do |form| %>
    <div class="row">
        <ul class="pt-5">
            <li>
                <%= link_to "Go Home - FedEx Labels", fedex_labels_path %>
            </li>
        </ul>
        <h1 class="pt-5 pb-3">New FedEx Label - Canada</h1>
        
        <div class="col-6">
            <h3>Shipper Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="shipper[name]" value="<%=@shipper[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="shipper[company]" value="<%=@shipper[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="shipper[phone_number]" value="<%=@shipper[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="shipper[address]" value="<%=@shipper[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="shipper[city]" value="<%=@shipper[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="shipper[state]" value="<%=@shipper[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="shipper[postal_code]" value="<%=@shipper[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text"  name="shipper[country_code]" value="<%=@shipper[:country_code] %>">
            </div>
        </div>
        <div class="col-6">
            <h3>Recipient Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="recipient[name]" value="<%=@recipient[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="recipient[company]" value="<%=@recipient[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="recipient[phone_number]" value="<%=@recipient[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="recipient[address]" value="<%=@recipient[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="recipient[city]" value="<%=@recipient[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="recipient[state]" value="<%=@recipient[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="recipient[postal_code]" value="<%=@recipient[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text" name="recipient[country_code]" value="<%=@recipient[:country_code] %>">
            </div>
            <div class="form-fild">
                <label>Residential :</label>
                <input type="text" name="recipient[residential]" value="<%=@recipient[:residential] %>">
            </div>
        </div>
        
    </div>
    <div class="row">
        <h3>Package Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @packages.inspect %>
        </code>
        
        <h3>Example Spec Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @example_spec.inspect %>
        </code>

        <h3>Shipping Options</h3>
        <hr/>
        <code class="pb-3">
            <%= @shipping_options.inspect %>
        </code>
        
        <h3>Customs Clearance Detail</h3>
        <hr/>
        <code class="pb-3">
            <%= @customs.inspect %>
        </code>
    </div>
    <div class="form-fild">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
    <% end %>

</div>



<script>
$('.form-fild input,.form-fild textarea').focus(function() {
    $(this).parent().addClass('open');
});

$('.form-fild input,.form-fild textarea').blur(function() {
    $(this).parent().removeClass('open');
});
</script>

app/views/fedex_labels/new_jp.html.erb
<div class="container">
    <%= form_with url: "/create_international", method: :post do |form| %>
    <div class="row">
        <ul class="pt-5">
            <li>
                <%= link_to "Go Home - FedEx Labels", fedex_labels_path %>
            </li>
        </ul>
        <h1 class="pt-5 pb-3">New FedEx Label - Japan</h1>
        
        <div class="col-6">
            <h3>Shipper Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="shipper[name]" value="<%=@shipper[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="shipper[company]" value="<%=@shipper[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="shipper[phone_number]" value="<%=@shipper[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="shipper[address]" value="<%=@shipper[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="shipper[city]" value="<%=@shipper[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="shipper[state]" value="<%=@shipper[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="shipper[postal_code]" value="<%=@shipper[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text"  name="shipper[country_code]" value="<%=@shipper[:country_code] %>">
            </div>
        </div>
        <div class="col-6">
            <h3>Recipient Address</h3>
            <hr/>
            <div class="form-fild">
                <label>Name :</label>
                <input type="text" name="recipient[name]" value="<%=@recipient[:name] %>">
            </div>
            <div class="form-fild">
                <label>Company :</label>
                <input type="text" name="recipient[company]" value="<%=@recipient[:company] %>">
            </div>
            <div class="form-fild">
                <label>Phone Number :</label>
                <input type="text" name="recipient[phone_number]" value="<%=@recipient[:phone_number] %>">
            </div>
            <div class="form-fild">
                <label>Address :</label>
                <input type="text" name="recipient[address]" value="<%=@recipient[:address] %>">
            </div>
            <div class="form-fild">
                <label>City :</label>
                <input type="text" name="recipient[city]" value="<%=@recipient[:city] %>">
            </div>
            <div class="form-fild">
                <label>State :</label>
                <input type="text" name="recipient[state]" value="<%=@recipient[:state] %>">
            </div>
            <div class="form-fild">
                <label>Postal Code :</label>
                <input type="text" name="recipient[postal_code]" value="<%=@recipient[:postal_code] %>">
            </div>
            <div class="form-fild">
                <label>Country Code :</label>
                <input type="text" name="recipient[country_code]" value="<%=@recipient[:country_code] %>">
            </div>
            <div class="form-fild">
                <label>Residential :</label>
                <input type="text" name="recipient[residential]" value="<%=@recipient[:residential] %>">
            </div>
        </div>
        
    </div>
    <div class="row">
        <h3>Package Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @packages.inspect %>
        </code>
        
        <h3>Example Spec Info</h3>
        <hr/>
        <code class="pb-3">
            <%= @example_spec.inspect %>
        </code>

        <h3>Shipping Options</h3>
        <hr/>
        <code class="pb-3">
            <%= @shipping_options.inspect %>
        </code>
        
        <h3>Customs Clearance Detail</h3>
        <hr/>
        <code class="pb-3">
            <%= @customs.inspect %>
        </code>
    </div>
    <div class="form-fild">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
    <% end %>
</div>



<script>
$('.form-fild input,.form-fild textarea').focus(function() {
    $(this).parent().addClass('open');
});

$('.form-fild input,.form-fild textarea').blur(function() {
    $(this).parent().removeClass('open');
});
</script>

app/views/fedex_labels/show.html.erb
<div class="container">

  <h1>FedEx Label Details </h1>
  <label>@image</label>
  <textarea rows="12"><%= @label.image %></textarea>
  <p><%= link_to "Download PDF", download_fedex_label_path(@label.id) %></p>
  <label>@options</label>
  <textarea rows="12"><%= @label.options %></textarea>
  <label>@response details</label>
  <textarea rows="12"><%= @label.response_details %></textarea>
  <ul>
      <%= link_to "Go Home - FedEx Labels", fedex_labels_path %>
  </ul>
  
</div>
  